name: localization_generator
description: Localization Generator
version: 1.0.0

environment:
  sdk: ^3.0.5

dependencies:
  change_case: ^1.0.0+3
  localization: ^2.1.0
  path: ^1.8.3

dev_dependencies:
  flutterando_analysis: ^0.0.2